CFLAGS = -Wall -Wextra -Werror -lncurses
CC = g++ -std=c++17
SOURCEFILE = main.cpp ../DynamicMemory/Source/OneDimensionalArray.cpp ../TwoDimensionalDynamicArray/Source/twodimensionalarray.cpp

all:
	$(CC) $(CFLAGS) $(SOURCEFILE) -o temp
	
	rm -rf *.o *.out
	